### ISSUE TITLE
2001: A Space Odyssey replies

### ISSUE THREAD

**Issue by The-Monkey-Sun-Wukong** [joepurdy/purdybot#3]
#2001: A Space Odyssey
##### Dave:

Open the pod bay doors, HAL.
##### HAL:

I'm sorry, Dave. I'm afraid I can't do that.

The most chilling reply in movie history! Can we add more replies to purdybot from the movie? What about...
##### User:

@purdybot Sing it for me.
#### Purdybot:

It's called "Daisy". [sings while slowing down] Dai-sy, dai-sy, give me your answer true. I'm half cra-zy, o-ver the love of you. It won't be a sty-lish mar-riage, I can't a-fford a car-riage---. But you'll look sweet upon the seat of a bicycle - built - for - two.

Or maybe...
#### User:

@purdybot What's the problem?
#### Purdybot:

I think you know what the problem is just as well as I do.

**Comment by joepurdy** [comment]
I added `@purdybot Sing it for me.` and `@purdybot What's the problem?` and merged them into production. The bot isn't on https://gitter.im/FreeCodeCamp/FreeCodeCamp anymore though, it's relocated to https://gitter.im/FreeCodeCamp/Casual
